let arr = [
  {
    category: "Programming",
    type: "twopart",
    setup: "Why did the programmer jump on the table?",
    delivery: "Because debug was on his screen.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 214,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Your momma is so fat, you need to switch to NTFS to store a picture of her.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 55,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "How do you tell HTML from HTML5?\n- Try it out in Internet Explorer\n- Did it work?\n- No?\n- It's HTML5.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 43,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: ".NET developers are picky when it comes to food.",
    delivery: "They only like chicken NuGet.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 49,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Java is like Alzheimer's, it starts off slow, but eventually, your memory is gone.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 27,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "The six stages of debugging:\n1. That can't happen.\n2. That doesn't happen on my machine.\n3. That shouldn't happen.\n4. Why does that happen?\n5. Oh, I see.\n6. How did that ever work?",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 123,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'Eight bytes walk into a bar.\nThe bartender asks, "Can I get you anything?"\n"Yeah," reply the bytes.\n"Make us a double."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 34,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'Two SQL tables sit at the bar. A query approaches and asks "Can I join you?"',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 221,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "How did the programmer die in the shower?",
    delivery: "He read the shampoo bottle instructions: Lather. Rinse. Repeat.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: false,
    id: 266,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'A SQL statement walks into a bar and sees two tables.\nIt approaches, and asks "may I join you?"',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 5,
    safe: true,
    lang: "en",
  },
];

let i = Math.floor(Math.random() *arr.length-1)
console.log(i);
joke.innerHTML=arr[i].joke;